apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migration
  namespace: riley
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migration
          image: awaistahseen009/riley-backend:v1.0.1
          command: ["alembic", "upgrade", "head"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: riley-secrets
                  key: DATABASE_URL