"""add meeting_format to meeting

Revision ID: 4de39e0ba2ae
Revises: 0258928eafd9
Create Date: 2026-04-29 10:45:29.778467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlmodel import SQLModel


# revision identifiers, used by Alembic.
revision: str = '4de39e0ba2ae'
down_revision: Union[str, Sequence[str], None] = '0258928eafd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('meeting_format', sa.VARCHAR(), server_default='virtual', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'meeting_format')
    # ### end Alembic commands ###
